services:
  heroku-cli:
    build: ./heroku
    env_file: ./heroku/.env

  db:
    build: ./db
    env_file: .env
    volumes:
      - ./db/init_data:/docker-entrypoint-initdb.d
      - reviews:/var/lib/postgresql/data  

  web:
    build: 
      context: ./
      dockerfile: Dockerfile
      target: devapp
    depends_on:
      - db                                      
    env_file: .env
    ports:
        - "3000:3000" 
    volumes:
      - ./src:/app/src
      
    

volumes:
  reviews: {}
